version = 0.1
[default.deploy.parameters]
stack_name = "delayed-wallet-app"
resolve_s3 = true
s3_prefix = "delayed-wallet-app"
region = "us-west-2"
profile = "default"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "BillingMode=\"PAY_PER_REQUEST\""
image_repositories = []
