// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	api "github.com/chris/delayed-wallet-transactions/pkg/api"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

// CreateTransaction provides a mock function with given fields: ctx, newTx
func (_m *Storage) CreateTransaction(ctx context.Context, newTx api.NewTransaction) (*api.Transaction, error) {
	ret := _m.Called(ctx, newTx)

	if len(ret) == 0 {
		panic("no return value specified for CreateTransaction")
	}

	var r0 *api.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, api.NewTransaction) (*api.Transaction, error)); ok {
		return rf(ctx, newTx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, api.NewTransaction) *api.Transaction); ok {
		r0 = rf(ctx, newTx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, api.NewTransaction) error); ok {
		r1 = rf(ctx, newTx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStuckTransactions provides a mock function with given fields: ctx, maxAge
func (_m *Storage) GetStuckTransactions(ctx context.Context, maxAge time.Duration) ([]api.Transaction, error) {
	ret := _m.Called(ctx, maxAge)

	if len(ret) == 0 {
		panic("no return value specified for GetStuckTransactions")
	}

	var r0 []api.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Duration) ([]api.Transaction, error)); ok {
		return rf(ctx, maxAge)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Duration) []api.Transaction); ok {
		r0 = rf(ctx, maxAge)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]api.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Duration) error); ok {
		r1 = rf(ctx, maxAge)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTransaction provides a mock function with given fields: ctx, txID
func (_m *Storage) GetTransaction(ctx context.Context, txID uuid.UUID) (*api.Transaction, error) {
	ret := _m.Called(ctx, txID)

	if len(ret) == 0 {
		panic("no return value specified for GetTransaction")
	}

	var r0 *api.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*api.Transaction, error)); ok {
		return rf(ctx, txID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *api.Transaction); ok {
		r0 = rf(ctx, txID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, txID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWallet provides a mock function with given fields: ctx, userID
func (_m *Storage) GetWallet(ctx context.Context, userID string) (*api.Wallet, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetWallet")
	}

	var r0 *api.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*api.Wallet, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *api.Wallet); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Wallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SettleTransaction provides a mock function with given fields: ctx, tx
func (_m *Storage) SettleTransaction(ctx context.Context, tx *api.Transaction) error {
	ret := _m.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for SettleTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *api.Transaction) error); ok {
		r0 = rf(ctx, tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
