// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// WebSocketManager is an autogenerated mock type for the WebSocketManager type
type WebSocketManager struct {
	mock.Mock
}

// AddConnection provides a mock function with given fields: ctx, connectionID
func (_m *WebSocketManager) AddConnection(ctx context.Context, connectionID string) error {
	ret := _m.Called(ctx, connectionID)

	if len(ret) == 0 {
		panic("no return value specified for AddConnection")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, connectionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllConnections provides a mock function with given fields: ctx
func (_m *WebSocketManager) GetAllConnections(ctx context.Context) ([]string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllConnections")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveConnection provides a mock function with given fields: ctx, connectionID
func (_m *WebSocketManager) RemoveConnection(ctx context.Context, connectionID string) error {
	ret := _m.Called(ctx, connectionID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveConnection")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, connectionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewWebSocketManager creates a new instance of WebSocketManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWebSocketManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *WebSocketManager {
	mock := &WebSocketManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
