// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	api "github.com/chris/delayed-wallet-transactions/pkg/api"

	mock "github.com/stretchr/testify/mock"
)

// Scheduler is an autogenerated mock type for the Scheduler type
type Scheduler struct {
	mock.Mock
}

// ScheduleTransaction provides a mock function with given fields: ctx, tx
func (_m *Scheduler) ScheduleTransaction(ctx context.Context, tx *api.Transaction) error {
	ret := _m.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for ScheduleTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *api.Transaction) error); ok {
		r0 = rf(ctx, tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewScheduler creates a new instance of Scheduler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewScheduler(t interface {
	mock.TestingT
	Cleanup(func())
}) *Scheduler {
	mock := &Scheduler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
